export enum JobStatus {
  PENDING = 'PENDING',
  CLONING = 'CLONING',
  INSTALLING = 'INSTALLING',
  ANALYZING = 'ANALYZING',
  ANALYSIS_COMPLETED = 'ANALYSIS_COMPLETED',
  GENERATING_TESTS = 'GENERATING_TESTS',
  TEST_GENERATION_COMPLETED = 'TEST_GENERATION_COMPLETED',
  CREATING_PR = 'CREATING_PR',
  PR_CREATION_COMPLETED = 'PR_CREATION_COMPLETED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
